export const QUICK_PHRASE_SUGGESTIONS = [
  "Bonjour",
  "Merci",
  "Oui",
  "Non",
  "J'ai besoin d'aide",
  "Je suis fatigué",
];

export const PREFIX_WORD_SUGGESTIONS = [
  "bonjour",
  "bonsoir",
  "bonne",
  "merci",
  "oui",
  "non",
  "je",
  "j'ai",
  "besoin",
  "aide",
  "s'il",
  "te",
  "plaît",
  "fatigué",
  "soif",
  "faim",
  "mal",
  "douleur",
  "voudrais",
  "boire",
  "manger",
  "toilette",
  "repos",
  "médicament",
  "infirmier",
  "médecin",
  "monsieur",
  "madame",
  "comment",
  "les",
  "beaucoup",
  "vite",
  "maintenant",
  "eau",
  "aider",
  "venir",
  "parler",
  "aller",
  "encore",
  "stop",
  "famille",
  "maman",
  "papa",
  "c'est",
  "ce",
  "comme",
];

export const NEXT_WORD_SUGGESTIONS = {
  bonjour: ["les", "monsieur", "madame", "comment"],
  bonsoir: ["les", "monsieur", "madame"],
  merci: ["beaucoup", "pour", "à", "de"],
  je: ["suis", "voudrais", "veux", "n'ai"],
  "j'ai": ["besoin", "mal", "faim", "soif"],
  besoin: ["d'aide", "de", "de vous"],
  "besoin d'aide": ["vite", "maintenant"],
  suis: ["fatigué", "prêt", "là", "désolé"],
  voudrais: ["boire", "manger", "parler", "aller"],
  peux: ["avoir", "parler", "venir"],
  tu: ["peux", "veux", "vas"],
  "tu peux": ["m'aider", "venir", "appeler", "me donner"],
  "tu peux m'aider": ["vite", "maintenant"],
  nous: ["allons", "devons", "pouvons"],
  aide: ["s'il", "vite", "maintenant"],
};

export const QUICK_SUGGESTIONS = QUICK_PHRASE_SUGGESTIONS;

export const WORD_SUGGESTIONS = [
  "Bonjour",
  "Bonsoir",
  "Bonne journée",
  "Merci",
  "S'il te plaît",
  "Je suis fatigué",
  "J'ai besoin d'aide",
  "Je voudrais boire",
  "Je voudrais manger",
  "Je suis en douleur",
  "Appelle-moi",
  "À plus tard",
];
