export const THEMES = {
  dark: {
    pageBackground: "linear-gradient(180deg, #0b1220 0%, #111827 100%)",
    cardBackground: "rgba(15, 23, 42, 0.94)",
    textColor: "#e5eefc",
    titleColor: "#f8fafc",
    subtitleColor: "#94a3b8",
    inputBackground: "#0a1020",
    inputBorder: "#334155",
    primaryButtonBackground: "linear-gradient(135deg, #2563eb, #1d4ed8)",
    secondaryButtonBackground: "#1e293b",
    secondaryButtonText: "#e2e8f0",
    accentColor: "#3b82f6",
    supportButtonBackground: "linear-gradient(135deg, #16a34a, #15803d)",
    recordingButtonBackground: "linear-gradient(135deg, #ef4444, #dc2626)",
    deleteButtonBackground: "#7f1d1d",
    deleteButtonBorder: "#b91c1c",
    deleteButtonText: "#fee2e2",
    infoBoxBackground: "rgba(30, 41, 59, 0.95)",
    mutedText: "#94a3b8",
    surfaceAlt: "rgba(2, 6, 23, 0.75)",
    categoryCardBackground: "#0f172a",
    categoryCardActiveBackground:
      "linear-gradient(180deg, rgba(37,99,235,0.25), rgba(15,23,42,1))",
    badgeSuccessBackground: "rgba(22, 163, 74, 0.18)",
    badgeSuccessText: "#86efac",
    badgeNeutralBackground: "rgba(51, 65, 85, 0.55)",
    badgeNeutralText: "#cbd5e1",
    floatingUrgencyBackground: "linear-gradient(135deg, #ef4444, #dc2626)",
  },

  light: {
    pageBackground: "linear-gradient(180deg, #f8fafc 0%, #e2e8f0 100%)",
    cardBackground: "rgba(255, 255, 255, 0.96)",
    textColor: "#0f172a",
    titleColor: "#020617",
    subtitleColor: "#475569",
    inputBackground: "#ffffff",
    inputBorder: "#cbd5e1",
    primaryButtonBackground: "linear-gradient(135deg, #2563eb, #1d4ed8)",
    secondaryButtonBackground: "#e2e8f0",
    secondaryButtonText: "#0f172a",
    accentColor: "#2563eb",
    supportButtonBackground: "linear-gradient(135deg, #16a34a, #15803d)",
    recordingButtonBackground: "linear-gradient(135deg, #ef4444, #dc2626)",
    deleteButtonBackground: "#fee2e2",
    deleteButtonBorder: "#ef4444",
    deleteButtonText: "#991b1b",
    infoBoxBackground: "#f1f5f9",
    mutedText: "#475569",
    surfaceAlt: "#f8fafc",
    categoryCardBackground: "#ffffff",
    categoryCardActiveBackground:
      "linear-gradient(180deg, rgba(37,99,235,0.12), rgba(255,255,255,1))",
    badgeSuccessBackground: "#dcfce7",
    badgeSuccessText: "#166534",
    badgeNeutralBackground: "#e2e8f0",
    badgeNeutralText: "#334155",
    floatingUrgencyBackground: "linear-gradient(135deg, #ef4444, #dc2626)",
  },

  colorful: {
    pageBackground:
      "linear-gradient(180deg, #1e1b4b 0%, #0f766e 50%, #111827 100%)",
    cardBackground: "rgba(30, 41, 59, 0.90)",
    textColor: "#fef3c7",
    titleColor: "#ffffff",
    subtitleColor: "#fde68a",
    inputBackground: "#111827",
    inputBorder: "#a78bfa",
    primaryButtonBackground: "linear-gradient(135deg, #f59e0b, #ef4444)",
    secondaryButtonBackground: "#312e81",
    secondaryButtonText: "#ffffff",
    accentColor: "#f59e0b",
    supportButtonBackground: "linear-gradient(135deg, #22c55e, #16a34a)",
    recordingButtonBackground: "linear-gradient(135deg, #fb7185, #e11d48)",
    deleteButtonBackground: "#7f1d1d",
    deleteButtonBorder: "#ef4444",
    deleteButtonText: "#fff1f2",
    infoBoxBackground: "rgba(49, 46, 129, 0.9)",
    mutedText: "#fde68a",
    surfaceAlt: "rgba(17, 24, 39, 0.78)",
    categoryCardBackground: "#1f2937",
    categoryCardActiveBackground:
      "linear-gradient(180deg, rgba(245,158,11,0.30), rgba(49,46,129,1))",
    badgeSuccessBackground: "rgba(34, 197, 94, 0.18)",
    badgeSuccessText: "#bbf7d0",
    badgeNeutralBackground: "rgba(99, 102, 241, 0.35)",
    badgeNeutralText: "#ffffff",
    floatingUrgencyBackground: "linear-gradient(135deg, #ef4444, #dc2626)",
  },
};

export function getActiveTheme(profile) {
  if (!profile) return THEMES.dark;

  if (profile.themeMode === "custom") {
    const custom = profile.customTheme || {};
    return {
      ...THEMES.dark,
      pageBackground: custom.pageBackground || THEMES.dark.pageBackground,
      cardBackground: custom.cardBackground || THEMES.dark.cardBackground,
      textColor: custom.textColor || THEMES.dark.textColor,
      titleColor:
        custom.titleColor || custom.textColor || THEMES.dark.titleColor,
      subtitleColor:
        custom.subtitleColor || custom.textColor || THEMES.dark.subtitleColor,
      inputBackground: custom.inputBackground || THEMES.dark.inputBackground,
      inputBorder: custom.inputBorder || THEMES.dark.inputBorder,
      primaryButtonBackground:
        custom.primaryButtonBackground || THEMES.dark.primaryButtonBackground,
      secondaryButtonBackground:
        custom.secondaryButtonBackground ||
        THEMES.dark.secondaryButtonBackground,
      secondaryButtonText:
        custom.secondaryButtonText || THEMES.dark.secondaryButtonText,
      accentColor: custom.accentColor || THEMES.dark.accentColor,
      supportButtonBackground:
        custom.supportButtonBackground || THEMES.dark.supportButtonBackground,
      recordingButtonBackground:
        custom.recordingButtonBackground ||
        THEMES.dark.recordingButtonBackground,
      deleteButtonBackground:
        custom.deleteButtonBackground || THEMES.dark.deleteButtonBackground,
      deleteButtonBorder:
        custom.deleteButtonBorder || THEMES.dark.deleteButtonBorder,
      deleteButtonText: custom.deleteButtonText || THEMES.dark.deleteButtonText,
      infoBoxBackground:
        custom.infoBoxBackground || THEMES.dark.infoBoxBackground,
      mutedText:
        custom.mutedText || custom.subtitleColor || THEMES.dark.mutedText,
      surfaceAlt: custom.surfaceAlt || THEMES.dark.surfaceAlt,
      categoryCardBackground:
        custom.categoryCardBackground || THEMES.dark.categoryCardBackground,
      categoryCardActiveBackground:
        custom.categoryCardActiveBackground ||
        THEMES.dark.categoryCardActiveBackground,
      badgeSuccessBackground:
        custom.badgeSuccessBackground || THEMES.dark.badgeSuccessBackground,
      badgeSuccessText: custom.badgeSuccessText || THEMES.dark.badgeSuccessText,
      badgeNeutralBackground:
        custom.badgeNeutralBackground || THEMES.dark.badgeNeutralBackground,
      badgeNeutralText: custom.badgeNeutralText || THEMES.dark.badgeNeutralText,
      floatingUrgencyBackground:
        custom.floatingUrgencyBackground ||
        THEMES.dark.floatingUrgencyBackground,
    };
  }

  return THEMES[profile.themeMode] || THEMES.dark;
}

export function createStyles(theme) {
  return {
    page: {
      minHeight: "100vh",
      background: theme.pageBackground,
      fontFamily: "Inter, Arial, sans-serif",
      padding: 12,
      color: theme.textColor,
    },
    container: {
      maxWidth: 1380,
      margin: "0 auto",
    },
    header: {
      display: "flex",
      justifyContent: "space-between",
      gap: 16,
      alignItems: "center",
      flexWrap: "wrap",
      marginBottom: 12,
    },
    title: {
      fontSize: 36,
      margin: 0,
      color: theme.titleColor,
      letterSpacing: "-0.03em",
      fontWeight: 800,
    },
    subtitle: {
      marginTop: 8,
      color: theme.subtitleColor,
      fontSize: 16,
      lineHeight: 1.5,
    },
    topButtons: {
      display: "flex",
      gap: 8,
      flexWrap: "wrap",
    },
    grid: {
      display: "grid",
      gridTemplateColumns: "1fr 1fr",
      gap: 10,
    },
    gridSingle: {
      display: "grid",
      gridTemplateColumns: "1fr",
      gap: 16,
    },
    card: {
      background: theme.cardBackground,
      borderRadius: 22,
      padding: 16,
      boxShadow: "0 20px 60px rgba(0,0,0,0.30)",
      border: `1px solid ${theme.inputBorder}`,
      backdropFilter: "blur(10px)",
    },
    sectionTitle: {
      marginTop: 0,
      marginBottom: 12,
      fontSize: 18,
      color: theme.titleColor,
      fontWeight: 800,
    },
    label: {
      color: theme.textColor,
      fontWeight: 700,
      fontSize: 16,
    },
    textarea: {
      width: "100%",
      minHeight: 180,
      padding: 16,
      borderRadius: 18,
      border: `2px solid ${theme.inputBorder}`,
      fontSize: 28,
      lineHeight: 1.4,
      boxSizing: "border-box",
      marginBottom: 18,
      background: theme.inputBackground,
      color: theme.textColor,
      outline: "none",
    },
    smallTextarea: {
      width: "100%",
      minHeight: 108,
      padding: 12,
      borderRadius: 16,
      border: `2px solid ${theme.inputBorder}`,
      fontSize: 18,
      boxSizing: "border-box",
      background: theme.inputBackground,
      color: theme.textColor,
      outline: "none",
      lineHeight: 1.5,
    },
    input: {
      width: "100%",
      padding: "8px 10px",
      borderRadius: 12,
      border: `2px solid ${theme.inputBorder}`,
      fontSize: 17,
      boxSizing: "border-box",
      marginTop: 6,
      background: theme.inputBackground,
      color: theme.textColor,
      outline: "none",
      minHeight: 44,
    },
    colorInput: {
      width: "100%",
      height: 48,
      padding: 6,
      borderRadius: 16,
      border: `2px solid ${theme.inputBorder}`,
      background: theme.inputBackground,
      boxSizing: "border-box",
      marginTop: 8,
      cursor: "pointer",
    },
    buttonGrid: {
      display: "grid",
      gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
      gap: 10,
      marginBottom: 12,
    },
    inlineButtons: {
      display: "flex",
      gap: 8,
      flexWrap: "wrap",
      alignItems: "center",
    },
    primaryButton: {
      background: theme.primaryButtonBackground,
      color: "white",
      border: "none",
      borderRadius: 18,
      padding: "12px 14px",
      cursor: "pointer",
      fontSize: 17,
      fontWeight: 800,
      boxShadow: "0 10px 24px rgba(0,0,0,0.18)",
      minHeight: 52,
    },
    secondaryButton: {
      background: theme.secondaryButtonBackground,
      color: theme.secondaryButtonText,
      border: `2px solid ${theme.inputBorder}`,
      borderRadius: 18,
      padding: "12px 14px",
      cursor: "pointer",
      fontSize: 17,
      fontWeight: 700,
      minHeight: 52,
    },
    supportButton: {
      background: theme.supportButtonBackground,
      color: "white",
      border: "none",
      borderRadius: 18,
      padding: "12px 14px",
      cursor: "pointer",
      fontSize: 19,
      fontWeight: 800,
      boxShadow: "0 10px 24px rgba(0,0,0,0.18)",
      minHeight: 52,
    },
    recordingButton: {
      background: theme.recordingButtonBackground,
      color: "white",
      border: "none",
      borderRadius: 18,
      padding: "12px 14px",
      cursor: "pointer",
      fontSize: 19,
      fontWeight: 800,
      boxShadow: "0 10px 24px rgba(0,0,0,0.18)",
      minHeight: 52,
    },
    deleteButton: {
      background: theme.deleteButtonBackground,
      color: theme.deleteButtonText,
      border: `1px solid ${theme.deleteButtonBorder}`,
      borderRadius: 10,
      padding: "6px 10px",
      cursor: "pointer",
      fontWeight: 800,
      fontSize: 12,
      minWidth: 78,
      height: 38,
    },
    favoriteButton: {
      width: 38,
      minWidth: 38,
      height: 38,
      borderRadius: 10,
      border: `2px solid ${theme.inputBorder}`,
      background: theme.inputBackground,
      color: "#facc15",
      fontSize: 18,
      cursor: "pointer",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      padding: 0,
    },
    smallActionButton: {
      background: theme.secondaryButtonBackground,
      color: theme.secondaryButtonText,
      border: `2px solid ${theme.inputBorder}`,
      borderRadius: 10,
      padding: "6px 8px",
      cursor: "pointer",
      fontSize: 14,
      fontWeight: 800,
      minWidth: 38,
      height: 38,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
    importLabel: {
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      background: theme.secondaryButtonBackground,
      color: theme.secondaryButtonText,
      border: `2px solid ${theme.inputBorder}`,
      borderRadius: 18,
      padding: "12px 14px",
      cursor: "pointer",
      fontSize: 16,
      fontWeight: 700,
      minHeight: 60,
    },
    formRow: {
      display: "grid",
      gridTemplateColumns: "1fr 1fr",
      gap: 10,
    },
    formGroup: {
      marginBottom: 12,
    },
    phraseEditorBox: {
      border: `1px solid ${theme.inputBorder}`,
      borderRadius: 22,
      padding: 12,
      background: theme.surfaceAlt,
    },
    infoBox: {
      background: theme.infoBoxBackground,
      padding: 14,
      borderRadius: 14,
      color: theme.textColor,
      lineHeight: 1.7,
      border: `1px solid ${theme.inputBorder}`,
      fontSize: 16,
    },
    readOnlyBox: {
      width: "100%",
      minHeight: 40,
      padding: "8px 10px",
      borderRadius: 10,
      background: theme.inputBackground,
      border: `1px solid ${theme.inputBorder}`,
      color: theme.textColor,
      lineHeight: 1.5,
      whiteSpace: "pre-wrap",
      boxSizing: "border-box",
      fontSize: 16,
    },
    recordingBox: {
      background: theme.surfaceAlt,
      border: `1px solid ${theme.inputBorder}`,
      borderRadius: 16,
      padding: 12,
      marginTop: 8,
    },
    recordingTitle: {
      color: theme.titleColor,
      fontSize: 18,
    },
    recordingText: {
      marginTop: 8,
      marginBottom: 12,
      color: theme.mutedText,
      fontSize: 16,
      lineHeight: 1.55,
    },
    recordingBadge: {
      display: "inline-block",
      background: theme.badgeSuccessBackground,
      color: theme.badgeSuccessText,
      padding: "8px 12px",
      borderRadius: 999,
      fontSize: 16,
      fontWeight: "bold",
      border: `1px solid ${theme.inputBorder}`,
    },
    noRecordingBadge: {
      display: "inline-block",
      background: theme.badgeNeutralBackground,
      color: theme.badgeNeutralText,
      padding: "8px 12px",
      borderRadius: 999,
      fontSize: 16,
      border: `1px solid ${theme.inputBorder}`,
    },
    filterTitle: {
      marginBottom: 10,
      fontWeight: 800,
      color: theme.textColor,
      fontSize: 16,
    },
    emptyText: {
      color: theme.mutedText,
      fontSize: 18,
    },
    categoryGrid: {
      display: "grid",
      gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
      gap: 8,
      marginTop: 8,
    },
    categoryCard: {
      background: theme.categoryCardBackground,
      border: `2px solid ${theme.inputBorder}`,
      borderRadius: 16,
      padding: 8,
      cursor: "pointer",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      gap: 4,
      minHeight: 60,
      fontSize: 12,
      transition: "all 0.2s ease",
      color: theme.textColor,
    },
    categoryCardActive: {
      border: `2px solid ${theme.accentColor}`,
      background: theme.categoryCardActiveBackground,
      boxShadow: "0 12px 24px rgba(0,0,0,0.12)",
    },
    categoryEmoji: {
      fontSize: 20,
      lineHeight: 1,
    },
    categoryLabel: {
      fontSize: 12,
      fontWeight: 700,
      textAlign: "center",
      color: theme.textColor,
    },
    quickPhraseGrid: {
      display: "grid",
      gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
      gap: 8,
      alignItems: "start",
    },
    quickPhraseCard: {
      display: "flex",
      flexDirection: "column",
      gap: 6,
      padding: 8,
      borderRadius: 16,
      background: theme.surfaceAlt,
      border: `1px solid ${theme.inputBorder}`,
    },
    quickPhraseButton: {
      width: "100%",
      minHeight: 52,
      border: "none",
      borderRadius: 14,
      color: "#ffffff",
      fontSize: 15,
      fontWeight: 800,
      lineHeight: 1.15,
      padding: "8px 10px",
      cursor: "pointer",
      boxShadow: "0 8px 16px rgba(0,0,0,0.18)",
    },
    quickPhraseActions: {
      display: "flex",
      gap: 6,
      alignItems: "center",
      justifyContent: "space-between",
      flexWrap: "nowrap",
    },
    categoryManagerBox: {
      background: theme.surfaceAlt,
      border: `1px solid ${theme.inputBorder}`,
      borderRadius: 16,
      padding: 14,
    },
    managerTitle: {
      marginTop: 0,
      marginBottom: 8,
      color: theme.titleColor,
      fontSize: 19,
      fontWeight: 800,
    },
    managerText: {
      marginTop: 0,
      marginBottom: 12,
      color: theme.mutedText,
      fontSize: 16,
      lineHeight: 1.55,
    },
    iconPickerGrid: {
      display: "grid",
      gridTemplateColumns: "repeat(6, minmax(0, 1fr))",
      gap: 8,
      marginTop: 8,
    },
    iconButton: {
      background: theme.categoryCardBackground,
      border: `2px solid ${theme.inputBorder}`,
      borderRadius: 16,
      minHeight: 52,
      fontSize: 24,
      cursor: "pointer",
      color: theme.textColor,
    },
    iconButtonActive: {
      border: `2px solid ${theme.accentColor}`,
      background: theme.categoryCardActiveBackground,
      boxShadow: "0 10px 20px rgba(0,0,0,0.12)",
    },
    customCategoryList: {
      marginTop: 16,
      display: "flex",
      flexDirection: "column",
      gap: 8,
    },
    customCategoryItem: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
      background: theme.surfaceAlt,
      border: `1px solid ${theme.inputBorder}`,
      borderRadius: 16,
      padding: 12,
    },
    customCategoryInfo: {
      display: "flex",
      alignItems: "center",
      gap: 10,
    },
    customCategoryIcon: {
      fontSize: 28,
    },
    customCategoryName: {
      fontSize: 16,
      fontWeight: 700,
      color: theme.titleColor,
    },
    urgentFloatingButton: {
      position: "fixed",
      right: 18,
      bottom: 18,
      background: theme.floatingUrgencyBackground,
      color: "white",
      border: "none",
      borderRadius: 20,
      padding: "14px 18px",
      fontSize: 17,
      fontWeight: 900,
      cursor: "pointer",
      boxShadow: "0 20px 40px rgba(239, 68, 68, 0.35)",
      zIndex: 1000,
    },
    themePreviewRow: {
      display: "flex",
      gap: 8,
      flexWrap: "wrap",
      marginTop: 10,
    },
    themePreviewChip: {
      padding: "10px 14px",
      borderRadius: 999,
      border: `1px solid ${theme.inputBorder}`,
      background: theme.surfaceAlt,
      color: theme.textColor,
      fontWeight: 700,
      fontSize: 14,
    },
  };
}
